name: Generate ESO Builds (Staggered)

on:
  schedule:
    # Every 30 minutes, cycling through all 14 trials
    # This means each trial gets updated every 7 hours
    - cron: '0 */2 * * *'   # Every 2 hours starting at minute 0
    - cron: '30 */2 * * *'  # Every 2 hours starting at minute 30
  workflow_dispatch:
    inputs:
      trial_id:
        description: 'Trial ID to scan (leave empty for auto-detect based on time)'
        required: false
        type: number

jobs:
  generate-trial:
    runs-on: ubuntu-latest
    steps:
      - name: Determine which trial to run
        id: trial
        run: |
          if [ -n "${{ inputs.trial_id }}" ]; then
            echo "trial_id=${{ inputs.trial_id }}" >> $GITHUB_OUTPUT
          else
            # Auto-detect based on current time (UTC) - cycles through all 14 trials every 28 hours
            # Each trial gets updated every 2 hours, staggered by 30 minutes
            MINUTE=$(date -u +%M)
            HOUR=$(date -u +%H)
            
            # Calculate which trial based on time
            # Every 2 hours, we cycle through 14 trials
            # Trial index = (hour / 2) % 14
            TRIAL_INDEX=$(( (HOUR / 2) % 14 ))
            
            # Adjust for 30-minute offset runs
            if [ "$MINUTE" -ge 30 ]; then
              TRIAL_INDEX=$(( (TRIAL_INDEX + 7) % 14 ))
            fi
            
            # Map trial index to actual trial IDs
            case $TRIAL_INDEX in
              0) echo "trial_id=1" >> $GITHUB_OUTPUT ;;   # AA
              1) echo "trial_id=2" >> $GITHUB_OUTPUT ;;   # HRC
              2) echo "trial_id=3" >> $GITHUB_OUTPUT ;;   # SO
              3) echo "trial_id=5" >> $GITHUB_OUTPUT ;;   # MoL
              4) echo "trial_id=6" >> $GITHUB_OUTPUT ;;   # HoF
              5) echo "trial_id=7" >> $GITHUB_OUTPUT ;;   # AS
              6) echo "trial_id=8" >> $GITHUB_OUTPUT ;;   # CR
              7) echo "trial_id=12" >> $GITHUB_OUTPUT ;;  # SS
              8) echo "trial_id=14" >> $GITHUB_OUTPUT ;;  # KA
              9) echo "trial_id=15" >> $GITHUB_OUTPUT ;;  # RG
              10) echo "trial_id=16" >> $GITHUB_OUTPUT ;;  # DSR
              11) echo "trial_id=17" >> $GITHUB_OUTPUT ;;  # SE
              12) echo "trial_id=18" >> $GITHUB_OUTPUT ;;  # LC
              13) echo "trial_id=19" >> $GITHUB_OUTPUT ;;  # OC
              *) echo "trial_id=1" >> $GITHUB_OUTPUT ;;    # Default to AA
            esac
            
            echo "Current time: $(date -u '+%H:%M') UTC"
            echo "Trial index: $TRIAL_INDEX"
          fi
      
      - name: Checkout main branch
        uses: actions/checkout@v4
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: output
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run build analysis for trial
        env:
          ESOLOGS_ID: ${{ secrets.ESOLOGS_ID }}
          ESOLOGS_SECRET: ${{ secrets.ESOLOGS_SECRET }}
        run: |
          python -m src.eso_build_o_rama.main --trial-id ${{ steps.trial.outputs.trial_id }}
      
      - name: Copy static assets
        run: |
          if [ ! -d "output/static" ]; then
            cp -r static output/
          fi
      
      - name: Commit and push changes
        working-directory: output
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update trial ${{ steps.trial.outputs.trial_id }} builds - $(date -u +%Y-%m-%d)"
            git push
          )
