name: Generate ESO Builds (Staggered)

on:
  schedule:
    # Every 30 minutes, cycling through all 14 trials sequentially
    # AA at 1:00 AM, HRC at 1:30 AM, SO at 2:00 AM, etc.
    # Each trial gets updated every 7 hours (14 trials × 30 minutes)
    - cron: '0,30 * * * *'  # Every 30 minutes
  workflow_dispatch:
    inputs:
      trial_id:
        description: 'Trial ID to scan (leave empty for auto-detect based on time)'
        required: false
        type: number

jobs:
  generate-trial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Determine which trial to run
        id: trial
        run: |
          if [ -n "${{ inputs.trial_id }}" ]; then
            echo "trial_id=${{ inputs.trial_id }}" >> $GITHUB_OUTPUT
          else
            # Sequential trial scheduling: AA, HRC, SO, MoL, HoF, AS, CR, SS, KA, RG, DSR, SE, LC, OC
            # Each trial runs every 24 hours (repeats the same sequence daily)
            # Starting reference: 20:32 UTC today for AA (cycle restarted)
            
            CURRENT_HOUR=$(date -u +%H | sed 's/^0*//' || echo "0")
            CURRENT_MINUTE=$(date -u +%M | sed 's/^0*//' || echo "0")
            
            # Minutes since 20:32 UTC today (restart reference)
            REFERENCE_HOUR=20
            REFERENCE_MINUTE=32
            TOTAL_MINUTES_SINCE_REFERENCE=$(( (CURRENT_HOUR - REFERENCE_HOUR) * 60 + CURRENT_MINUTE - REFERENCE_MINUTE ))
            
            # Handle negative values (if current time is before reference)
            if [ $TOTAL_MINUTES_SINCE_REFERENCE -lt 0 ]; then
              TOTAL_MINUTES_SINCE_REFERENCE=$((TOTAL_MINUTES_SINCE_REFERENCE + 24 * 60))
            fi
            
            # Trial index = (minutes since reference / 30) % 14
            TRIAL_INDEX=$(( (TOTAL_MINUTES_SINCE_REFERENCE / 30) % 14 ))
            
            # Map trial index to actual trial IDs
            case $TRIAL_INDEX in
              0) echo "trial_id=1" >> $GITHUB_OUTPUT ;;   # AA
              1) echo "trial_id=2" >> $GITHUB_OUTPUT ;;   # HRC
              2) echo "trial_id=3" >> $GITHUB_OUTPUT ;;   # SO
              3) echo "trial_id=5" >> $GITHUB_OUTPUT ;;   # MoL
              4) echo "trial_id=6" >> $GITHUB_OUTPUT ;;   # HoF
              5) echo "trial_id=7" >> $GITHUB_OUTPUT ;;   # AS
              6) echo "trial_id=8" >> $GITHUB_OUTPUT ;;   # CR
              7) echo "trial_id=12" >> $GITHUB_OUTPUT ;;  # SS
              8) echo "trial_id=14" >> $GITHUB_OUTPUT ;;  # KA
              9) echo "trial_id=15" >> $GITHUB_OUTPUT ;;  # RG
              10) echo "trial_id=16" >> $GITHUB_OUTPUT ;;  # DSR
              11) echo "trial_id=17" >> $GITHUB_OUTPUT ;;  # SE
              12) echo "trial_id=18" >> $GITHUB_OUTPUT ;;  # LC
              13) echo "trial_id=19" >> $GITHUB_OUTPUT ;;  # OC
              *) echo "trial_id=1" >> $GITHUB_OUTPUT ;;    # Default to AA
            esac
            
            echo "Current time: $(date -u '+%Y-%m-%d %H:%M') UTC"
            echo "Minutes since 20:32 UTC (restart reference): $TOTAL_MINUTES_SINCE_REFERENCE"
            echo "Trial index: $TRIAL_INDEX"
          fi
      
      - name: Checkout main branch
        uses: actions/checkout@v4
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: output
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run build analysis for trial
        env:
          ESOLOGS_ID: ${{ secrets.ESOLOGS_ID }}
          ESOLOGS_SECRET: ${{ secrets.ESOLOGS_SECRET }}
        run: |
          python -m src.eso_build_o_rama.main --trial-id ${{ steps.trial.outputs.trial_id }}
      
      - name: Copy static assets
        run: |
          if [ ! -d "output/static" ]; then
            cp -r static output/
          fi
      
      - name: Commit and push changes
        working-directory: output
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update trial ${{ steps.trial.outputs.trial_id }} builds - $(date -u +%Y-%m-%d)"
            git push
          )
